
# render.yaml
databases:
  - name: django-postgres
    plan: free

services:
  - type: web
    name: django-web
    env: python
    plan: free
    autoDeploy: true
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py migrate --noinput && gunicorn deporte.wsgi:application --bind 0.0.0.0:10000
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: deporte.settings
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: django-postgres
          property: connectionString
